Repository TomyRioss/backendito, pull requests merged in 2025-01, with the labels that each got.

#3 Refactor: 🏗 Changes in file and folder structure
  src/app/about/page.tsx
  src/app/components/HomeHeader/HomeHeader.module.css
  src/app/components/HomeHeader/HomeHeader.tsx
  src/app/components/HomepageServices/HomepageServices.tsx
  src/app/contact/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/services/page.tsx
  src/components/About/About.tsx
  src/components/Home/Contact.tsx
  src/components/Home/Hero.tsx
  src/components/Home/Info.tsx
  src/components/Home/Services.tsx
  src/components/Home/Services_Info.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Navbar.tsx
  src/lib/services.ts
  src/styles/about.css
  src/utils/menusList.ts
  tsconfig.json
Labels: ref, desig

#5 Feature/add themes to backendito
  src/@types/app.d.ts
  src/@types/theme.d.ts
  src/app/components/Navbar/Navbar.tsx
  src/app/layout.tsx
  src/components/ui/customButton.tsx
  src/shared/styles/shared.ts
  src/shared/styles/themes/darkTheme.ts
  src/shared/styles/themes/lightTheme.ts
  src/shared/styles/themes/themeProvider.tsx
  tailwind.config.ts
Labels: enhancement

#6 Bugfix/merge develop with main
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/about/page.tsx
  src/app/components/HomeHeader/HomeHeader.module.css
  src/app/components/HomeHeader/HomeHeader.tsx
  src/app/contact/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/services/page.tsx
  src/components/About/About.tsx
  src/components/Home/Contact.tsx
  src/components/Home/Hero.tsx
  src/components/Home/Info.tsx
  src/components/Home/Services.tsx
  src/components/Home/Services_Info.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Navbar.tsx
  src/lib/services.ts
  src/shared/styles/about.css
  src/shared/utils/menusList.ts
Labels: bugfix

#7 Feature/add language selector dropdown
  src/@types/app.d.ts
  src/components/Layout/Navbar.tsx
  src/components/ui/dropdown.tsx
  src/i18n/config.ts
  src/i18n/request.ts
  src/shared/utils/getUserLocale.ts
Labels: enhancement

#15 about page created and modified
  package.json
  pnpm-lock.yaml
  src/app/about/page.tsx
  src/components/About/About.tsx
  src/components/About/fade-in.tsx
  tailwind.config.ts
Labels: desig

#18 Hotfix/fix toggle theme and local
  src/app/globals.css
  src/components/Layout/Navbar.tsx
  src/components/ui/LanguageDropdownSwitcher.tsx
  src/shared/styles/themes/themeProvider.tsx
  src/shared/utils/useMenusList.ts
Labels: enhancement, bugfix

#17 Hotfix/fix toggle theme and local
  src/app/globals.css
  src/components/Layout/Navbar.tsx
  src/components/ui/LanguageDropdownSwitcher.tsx
  src/shared/styles/themes/themeProvider.tsx
  src/shared/utils/useMenusList.ts
Labels: enhancement, bugfix
